plugins {
    id 'com.android.application'
}

android {
    namespace 'com.alexzab.z80pocketide'
    compileSdk 35

    defaultConfig {
        applicationId 'com.alexzab.z80pocketide'
        minSdk 23
        targetSdk 35
        versionCode 13
        versionName '0.12.0'

        testInstrumentationRunner 'android.test.InstrumentationTestRunner'
    }
}

dependencies {
    testImplementation 'junit:junit:4.13.2'
}
